namespace: monk-wordpress

stack:
  defines: process-group
  runnable-list:
    - monk-wordpress/db
    - monk-wordpress/web
  variables:
    wordpress-db-user: "db_user"
    wordpress-db-password: "RhgDPXPEnAgJ5q5g"
    wordpress-db-name: "wpdb"
    mysql-root-password: "RhgDPXPEnAgJ5q5g"
    db-data-path: <- `${monk-volume-path}/mysql/db`