namespace: monk-wordpress


stack:
  defines: process-group
  runnable-list:
    - monk-wordpress/db
    - monk-wordpress/web
  variables:
    mysql_user: "db_user"
    mysql_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database: "wpdb"
    mysql_password: "RhgDPXPEnAgxxXYZ"
    rpc-port: 80
