namespace: monk-wordpress

group-variables:
    wordpress-db-user: db_user
    wordpress-db-password:
      type: string
      value: "RhgDPXPEnAgJ5q5g"
    wordpress-db-name:
      env: MYSQL_DATABASE
      type: string
      value: "wpdb"
    mysql-root-password:
      env: MYSQL_ROOT_PASSWORD
      type: string
      value: "RhgDPXPEnAgJ5q5g"
    db-data-path:
      type: string
      value: <- `${monk-volume-path}/mysql/db`

stack:
  defines: process-group
  runnable-list:
    - monk-wordpress/db
    - monk-wordpress/web
  variables:
    inherits: ./group-variables

    